### PR TITLE
ROCANA-9120: commit initial Lucene code for rocana-lucene-codec

### PR DESCRIPTION
**Pull request by bradcupit**
This is the Lucene code completely untouched, extracted from lucene-core-5.5.0-sources.jar (groupId: org.apache.lucene, artifactId: lucene-core)

In a future commit these will be tweaked, but committing them like this, in their pristine state, lets us see exactly what Rocana changed just via a simple history diff.

### CODE REVIEW

**Comment by mpeterson0x0** [comment]
Are we going to:

1) put these in Rocana packages?
2) change the names of any of these files? (e.g., `BlockTreeTermsReader` -> `RocanaBlockTreeTermsReader`
?

If yes, should we do that now for the later diff you are targeting with this PR?

**Comment by mpeterson0x0** [comment]
Also are there unit tests for these in the Lucene codebase we should pull over?

**Comment by bradcupit** [comment]
Answers:
1. put these in Rocana packages? **yes**
2. change the names of any of these files? (e.g., BlockTreeTermsReader -> RocanaBlockTreeTermsReader) **no. I originally used RocanaForkOfBlockTreeTermsReader, but I asked Joey and since it's in a rocana package and the repo/jar is rocana-lucene-codec it's kind of redundant.**
3. should we do that now? **I'm relying on git's rename tracking. If I rename them now the build will break, unless I also modify the `package` in the files, but then that breaks the sated purpose of this PR)**
4. are there unit tests for these in the Lucene codebase? **Not in the jar, but I can look in github**

**Comment by mpeterson0x0** [comment]
> change the names of any of these files? (e.g., BlockTreeTermsReader -> RocanaBlockTreeTermsReader) no. I originally used RocanaForkOfBlockTreeTermsReader, but I asked Joey and since it's in a rocana package and the repo/jar is rocana-lucene-codec it's kind of redundant.

Harkening back to the discussion in the last PR, Java packages are mostly invisible from a reader point of view, so I generally favor changing the class name, so that's my vote, but if you and Joey feel strongly about it, it's not a deal breaker.

> I'm relying on git's rename tracking. If I rename them now the build will break, unless I also modify the package in the files, but then that breaks the sated purpose of this PR)

I don't follow why it breaks the build, but if you are sure that Git will handle it correctly, then I'm good.

> Not in the jar, but I can look in github

Make sure you checkout the 5.5.0 tag when you pull it down. I have it pulled down already, so I can help look those up if you'd like.

**Comment by bradcupit** [comment]
good news:
1. the git rename seems to work as hoped
2. i found a few tests, and they all pass

The only open question is on whether we put Rocana in the name (RocanaBlockTreeTermsReader vs BlockTreeTermsReader). I didn't get the impression Joey was passionate about it. In any case file renames would come in the next commit.

**Review by mpeterson0x0 — APPROVED** [review]
+1, LGTM

**Pull request merged**
