### PR TITLE
ROCANA-9285: publish rocana-lucene-codec-1.0.0 final and update RS pom

### PR DESCRIPTION
**Pull request by bradcupit**
This is one JIRA but two pull requests: one for the main rocana repo and one for the rocana-lucene-codec repo. Once both PRs are approved I will:
1. merge the rocana-lucene-codec PR
2. publish rocana-lucene-codec -1.0.0 by running the Jenkins job
3. merge the main rocana repo PR

### CODE REVIEW

**Comment by matthew-dailey** [comment]
@bradcupit when you're ready to release, I think the intent is to use the release [Jenkins job](https://jenkins.scalingdata.com:8443/job/rocana-lucene-codec-release/build?delay=0sec) which will up the version, deploy, then up the version again to the development version.  The work is done in [release.sh](https://github.com/scalingdata/rocana-lucene-codec/blob/master/release.sh), which is called by the Jenkins job

**Comment by bradcupit** [comment]
Thanks @matthew-dailey !
[ROCANA-9444](https://scalingdata.atlassian.net/browse/ROCANA-9444) is the JIRA to bump it up to 1.0.1-SNAPSHOT

**Comment by matthew-dailey** [comment]
The bump to 1.0.1-SNAPSHOT is also handled by the Jenkins job.  I don't think there needs to be a PR for the 1.0.0 bump *or* the 1.0.1-SNAPSHOT bump because Jenkins handles it

**Comment by bradcupit** [comment]
Oh nice! Thanks for clearing that up!! 👏

**Comment by matthew-dailey** [comment]
All that being said; we haven't tested this particular Jenkins job because doing so would perform a release :)

**Comment by bradcupit** [comment]
😳

**Comment by joey** [comment]
@bradcupit what I've done in the past is run a release build that creates a `1.0.0-rc1` version but then reset the current version to `1.0.0-SNAPSHOT`. If that works, then I do a release of `1.0.0` and set the next development version to `1.0.1-SNAPSHOT`

**Comment by bradcupit** [comment]
This PR will never get merged. The functionality here is already present in the Jenkins build that does the release. It updates the pom version number (ex: 1.0.0), commits, pushes, then updates it again (ex: 1.0.1-SNAPSHOT)

**Pull request closed without merging**
